# Generated by Django 2.0.5 on 2018-08-25 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=8, null=True)),
                ('vno', models.IntegerField(default=1)),
                ('insdate', models.DateTimeField(auto_now_add=True)),
                ('upddate', models.DateTimeField(blank=True, null=True)),
                ('insuser', models.CharField(blank=True, max_length=100, null=True)),
                ('upduser', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vno', models.IntegerField(default=1)),
                ('insdate', models.DateTimeField(auto_now_add=True)),
                ('upddate', models.DateTimeField(blank=True, null=True)),
                ('insuser', models.CharField(blank=True, max_length=100, null=True)),
                ('upduser', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Junle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vno', models.IntegerField(default=1)),
                ('insdate', models.DateTimeField(auto_now_add=True)),
                ('upddate', models.DateTimeField(blank=True, null=True)),
                ('insuser', models.CharField(blank=True, max_length=100, null=True)),
                ('upduser', models.CharField(blank=True, max_length=100, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching_place.Job')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginid', models.CharField(max_length=200)),
                ('mail_address', models.EmailField(blank=True, max_length=200, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=16, null=True)),
                ('tel', models.CharField(blank=True, max_length=12, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, default='1', max_length=1, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=8, null=True)),
                ('address1', models.CharField(blank=True, max_length=200, null=True)),
                ('address2', models.CharField(blank=True, max_length=200, null=True)),
                ('address3', models.CharField(blank=True, max_length=200, null=True)),
                ('area1', models.CharField(blank=True, max_length=5, null=True)),
                ('area2', models.CharField(blank=True, max_length=5, null=True)),
                ('area3', models.CharField(blank=True, max_length=5, null=True)),
                ('area4', models.CharField(blank=True, max_length=5, null=True)),
                ('area5', models.CharField(blank=True, max_length=5, null=True)),
                ('junle1', models.CharField(blank=True, max_length=5, null=True)),
                ('junle2', models.CharField(blank=True, max_length=5, null=True)),
                ('junle3', models.CharField(blank=True, max_length=5, null=True)),
                ('junle4', models.CharField(blank=True, max_length=5, null=True)),
                ('junle5', models.CharField(blank=True, max_length=5, null=True)),
                ('weekday1', models.CharField(blank=True, default='1', max_length=1, null=True)),
                ('weekday2', models.CharField(blank=True, default='1', max_length=1, null=True)),
                ('weekday3', models.CharField(blank=True, default='1', max_length=1, null=True)),
                ('weekday4', models.CharField(blank=True, default='1', max_length=1, null=True)),
                ('weekday5', models.CharField(blank=True, default='1', max_length=1, null=True)),
                ('time_from1', models.TimeField(blank=True, null=True)),
                ('time_from2', models.TimeField(blank=True, null=True)),
                ('time_from3', models.TimeField(blank=True, null=True)),
                ('time_from4', models.TimeField(blank=True, null=True)),
                ('time_from5', models.TimeField(blank=True, null=True)),
                ('time_to1', models.TimeField(blank=True, null=True)),
                ('time_to2', models.TimeField(blank=True, null=True)),
                ('time_to3', models.TimeField(blank=True, null=True)),
                ('time_to4', models.TimeField(blank=True, null=True)),
                ('time_to5', models.TimeField(blank=True, null=True)),
                ('vno', models.IntegerField(default=1)),
                ('insdate', models.DateTimeField(auto_now_add=True)),
                ('upddate', models.DateTimeField(blank=True, null=True)),
                ('insuser', models.CharField(blank=True, max_length=100, null=True)),
                ('upduser', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matching_place.Area')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matching_place.Job')),
                ('junle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matching_place.Junle')),
            ],
            options={
                'ordering': ('insdate',),
            },
        ),
    ]
