# Generated by Django 2.0.5 on 2018-08-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching_place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mail_address',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
