# Generated by Django 2.0.5 on 2018-08-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching_place', '0002_auto_20180823_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', '女性'), ('2', '男性')], default='1', max_length=1, null=True),
        ),
    ]
