# Generated by Django 2.0.5 on 2018-08-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching_place', '0004_auto_20180823_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, default='1', max_length=1, null=True),
        ),
    ]
